# Generated by Django 5.1.4 on 2024-12-20 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=17, unique=True)),
                ('number_cnh', models.CharField(max_length=20)),
                ('category_cnh', models.CharField(max_length=2)),
                ('telefone', models.CharField(max_length=20)),
            ],
        ),
    ]
