# Generated by Django 5.1.4 on 2024-12-20 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driver_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='status',
        ),
        migrations.AddField(
            model_name='driver',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
