# Generated by Django 5.1.4 on 2024-12-20 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0005_rename_telefone_driver_phone'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='current_location',
            field=models.CharField(choices=[('rua', 'Rua'), ('garagem', 'Garagem'), ('manutencao', 'Manutenção')], default='garagem', max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drivers.driver'),
        ),
    ]
