# Generated by Django 5.1.4 on 2024-12-20 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0005_rename_telefone_driver_phone'),
        ('vehicles', '0002_vehicle_current_location_vehicle_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drivers.driver'),
        ),
    ]
