# Generated by Django 5.1.4 on 2024-12-20 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_vehicle_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='current_location',
            field=models.CharField(choices=[('Rua', 'Rua'), ('Garagem', 'Garagem'), ('Manutencao', 'Manutenção')], default='garagem', max_length=100),
        ),
    ]
